### ISSUE TITLE
A couple of potential security bugs

### ISSUE THREAD

**Issue by nalind** [mit-athena/libhesiod#2]
Hi, I got a couple of bug reports today that affect the client library.  [#1332508](https://bugzilla.redhat.com/show_bug.cgi?id=1332508)  is largely about checks that we have around getenv() no longer being sufficient, and [#1332493](https://bugzilla.redhat.com/show_bug.cgi?id=1332493) is about avoiding inadvertently switching to querying MIT's hesiod data.

Is this the right place for discussing proposed fixes?

**Comment by achernya** [comment]
The official upstream repository for hesiod is https://github.com/achernya/hesiod, this is just a mirror.

**Comment by nalind** [comment]
Thanks!  I'll follow up there.
